[package]
name = "wtinylfu"
version = "0.3.0"
authors = ["asyncth <asyncthry@gmail.com>"]
edition = "2021"
description = "An implementation of W-TinyLFU cache"
readme = "README.md"
repository = "https://github.com/asyncth/wtinylfu"
license = "MIT"
keywords = ["cache", "lru", "lfu", "tinylfu", "w-tinylfu"]
categories = ["algorithms", "caching", "data-structures"]

[profile.release]
codegen-units = 1
lto = true

[dependencies]
bloomfilter = "3"
count-min-sketch = "0.1.8"
lru = { version = "0.16.2", default-features = false }
